### ISSUE TITLE
Can we get a release bump?

### ISSUE THREAD

**Issue by equalsraf** [lubyk/xml#3]
Can we get a release bump? to get the Windows fixes from #2 working with luarocks.

**Comment by gaspard** [comment]
Thanks for the reminder. Done, version 1.1.2 contains your fix. Thanks !

BTW: all lubyk modules use lut.Builder to prepare builds for luarocks, CMake, luadist, etc. I had to move your changes to lut/init.lua.
http://doc.lubyk.org/lut.Builder.html
